### PR TITLE
Fix of installation

### PR DESCRIPTION
**Pull request by MXNXV-ERR**
Specific Version fails the installation due to incompatible commands in newer version of python

### CODE REVIEW

**Comment by cameronperot** [comment]
Thanks for letting me know. Unfortunately, I haven't had the time to maintain this package after open sourcing the repo, but I have implemented some changes in https://github.com/cameronperot/qbm/pull/2 to help get it working again. I'll try to see if I can find the time to improve the installation process and testing going forward.

**Comment by MXNXV-ERR** [comment]
Hey thanks for response , Also would like some help understanding how QBM works would be possible to connect by any means ...

**Comment by cameronperot** [comment]
If you haven't read [Quantum Boltzmann Machine by Amin et al.](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.8.021050) then I would suggest starting there. I also wrote about how they work in my master's thesis [Quantum Boltzmann Machines: Applications in Quantitative Finance](https://arxiv.org/abs/2301.13295).

**Comment by MXNXV-ERR** [comment]
Hello Cameron,

I have gone through your master thesis :Quantum Boltzmann Machines :Applications in Quantitative Finance , I am inspired by your work and i am trying to use the RBM for Generation of Anomaly samples on Intrusion detection dataset, i tried to use your work to fit my data and some part of the code requires config.json and embedding.json to run the QBM , i am unable to locate the respective files in your repository , It would be great if you could assist me with this .
Another observation when i tried with no embeddings i found that the size i could go to encode my data with n-bit is very limited , can this be resolved?? 

My data after binarization has shape of ( 7361 , 740 ),,

It would be great if you could assist me with my understanding about RBM and QBM.........

**Pull request closed without merging**
